// Full bet reference. Edge values are Monte-Carlo-verified (see test/simulate.js)
// and derive from the 36-outcome dice space. "res" = how the bet resolves.
// Entries affected by table rules (Field paytable, Buy/Lay vig convention) are
// generated by getBetReference(rules) below rather than hardcoded once, so the
// reference table always matches whatever variant is selected in the app.
const STATIC_BETS = [
  { name: "Don't Pass / Don't Come", pays: "1 : 1", pwin: "47.9%", edge: 1.36, res: "per decision", grp: "Line", note: "Lowest edge on the table. 12 pushes (the bar). You become the favorite once a point is set." },
  { name: "Pass Line / Come", pays: "1 : 1", pwin: "49.3%", edge: 1.41, res: "per decision", grp: "Line", note: "Come-out: 7/11 win, 2/3/12 lose. Point set → make it before a 7." },
  { name: "Odds — 6 / 8", pays: "6 : 5", pwin: "45.5%", edge: 0, res: "free", grp: "Odds", note: "True odds, zero edge. The only free bet in the casino. Load these." },
  { name: "Odds — 5 / 9", pays: "3 : 2", pwin: "40.0%", edge: 0, res: "free", grp: "Odds", note: "True odds. Requires a Pass/Come bet in front of it." },
  { name: "Odds — 4 / 10", pays: "2 : 1", pwin: "33.3%", edge: 0, res: "free", grp: "Odds", note: "True odds. Highest-variance odds — biggest swings, still 0% edge." },
  { name: "Lay Odds (Don't)", pays: "1:2 / 2:3 / 5:6", pwin: "—", edge: 0, res: "free", grp: "Odds", note: "Don't-side true odds. Lay more to win less; low variance, 0% edge." },
  { name: "Place 6 / 8", pays: "7 : 6", pwin: "45.5%", edge: 1.52, res: "per resolution", grp: "Place", note: "Best number bet. Bet in $6 units or you lose payout to rounding." },
  { name: "Place 5 / 9", pays: "7 : 5", pwin: "40.0%", edge: 4.0, res: "per resolution", grp: "Place", note: "Bet in $5 units. Middling cost — buy them instead if vig is on the win." },
  { name: "Place 4 / 10", pays: "9 : 5", pwin: "33.3%", edge: 6.67, res: "per resolution", grp: "Place", note: "Buy these instead — same bet, cheaper either vig convention." },
  { name: "Big 6 / 8", pays: "1 : 1", pwin: "45.5%", edge: 9.09, res: "per resolution", grp: "Trap", note: "Place 6/8 with the edge multiplied 6×. Same outcome, worse pay. Never." },
  { name: "Hard 6 / 8", pays: "9 : 1", pwin: "9.1%", edge: 9.09, res: "multi-roll", grp: "Hard", note: "Win only on 3-3 / 4-4 before any other 6/8 or a 7." },
  { name: "Any Craps", pays: "7 : 1", pwin: "11.1%", edge: 11.11, res: "per roll", grp: "Prop", note: "One-roll on 2/3/12. Common come-out hedge — the hedge costs EV." },
  { name: "C & E", pays: "3:1 / 7:1", pwin: "16.7%", edge: 11.11, res: "per roll", grp: "Prop", note: "Half Any Craps, half Eleven. Two bad bets in a trench coat." },
  { name: "Hard 4 / 10", pays: "7 : 1", pwin: "11.1%", edge: 11.11, res: "multi-roll", grp: "Hard", note: "Win only on 2-2 / 5-5 before the easy way or a 7." },
  { name: "Yo (11)", pays: "15 : 1", pwin: "5.6%", edge: 11.11, res: "per roll", grp: "Prop", note: "One-roll on 11." },
  { name: "Ace-Deuce (3)", pays: "15 : 1", pwin: "5.6%", edge: 11.11, res: "per roll", grp: "Prop", note: "One-roll on 3." },
  { name: "Horn", pays: "15:1 / 30:1", pwin: "11.1%", edge: 12.5, res: "per roll", grp: "Prop", note: "One unit each on 2/3/11/12. Three of four units lose every roll." },
  { name: "World / Whirl", pays: "combo", pwin: "—", edge: 13.33, res: "per roll", grp: "Prop", note: "Horn + Any Seven in one 5-unit bet. A 7 is a wash (the any-7 leg exactly refunds the other four); worse than a plain Horn." },
  { name: "Aces / Boxcars", pays: "30 : 1", pwin: "2.8%", edge: 13.89, res: "per roll", grp: "Prop", note: "One-roll on 2 or 12. A 1-in-36 shot paying 30." },
  { name: "Any Seven", pays: "4 : 1", pwin: "16.7%", edge: 16.67, res: "per roll", grp: "Prop", note: "The single worst bet on the table. 5:1 shot paying 4:1." },
];

// Single source of truth for the rule-dependent number edges, reused by the
// reference table below and by the live "expected drag" readout in App.jsx /
// Table.jsx — so the tile labels and the reference table can never drift out
// of sync with each other. See engine.js for the vig-always derivation.
export const PLACE_EDGE = { 4: 6.67, 10: 6.67, 5: 4.0, 9: 4.0, 6: 1.52, 8: 1.52 };
export function buyEdge(vigAlways) {
  return vigAlways
    ? { 4: 3.33, 10: 3.33, 5: 3.0, 9: 3.0, 6: 2.73, 8: 2.73 }
    : { 4: 1.67, 10: 1.67, 5: 2.0, 9: 2.0, 6: 2.27, 8: 2.27 };
}
export function layEdge(vigAlways) {
  return vigAlways
    ? { 4: 0.83, 10: 0.83, 5: 1.33, 9: 1.33, 6: 1.89, 8: 1.89 }
    : { 4: 1.67, 10: 1.67, 5: 2.0, 9: 2.0, 6: 2.27, 8: 2.27 };
}
export const fieldEdge = (fieldTriple) => (fieldTriple ? 2.78 : 5.56);

function fieldBets(fieldTriple) {
  return fieldTriple
    ? [{ name: "Field (12 pays 3:1)", pays: "1:1 / 2:1 / 3:1", pwin: "44.4%", edge: 2.78, res: "per roll", grp: "Field", note: "Looks like it covers 7 numbers, but the common 5/6/7/8 all lose." }]
    : [{ name: "Field (12 pays 2:1)", pays: "1:1 / 2:1", pwin: "44.4%", edge: 5.56, res: "per roll", grp: "Field", note: "The worse, more common Field paytable — read the felt before betting. Doubles the edge of the 3:1 version." }];
}

// Buy/Lay edges depend on the vig convention. Vig-on-win varies by number
// (1.67%-2.27%); vig-always is a flat cost amortized over the bet's lifetime,
// which works out cheaper for Lay bets and pricier for Buy bets — see the
// derivation in engine.js and the Monte-Carlo checks in test/simulate.js.
function buyLayBets(vigAlways) {
  const bE = buyEdge(vigAlways), lE = layEdge(vigAlways);
  if (!vigAlways) {
    return [
      { name: "Buy 4 / 10", pays: "2:1 − 5%", pwin: "33.3%", edge: bE[4], res: "per resolution", grp: "Buy", note: "True odds minus 5% vig on the win only. Beats Place 4/10 (6.67%)." },
      { name: "Lay 4 / 10", pays: "1:2 − 5%", pwin: "66.7%", edge: lE[4], res: "per resolution", grp: "Lay", note: "Wrong-side bet on 4/10. Edge on amount risked. You're the favorite." },
      { name: "Buy 5 / 9", pays: "3:2 − 5%", pwin: "40.0%", edge: bE[5], res: "per resolution", grp: "Buy", note: "Marginally worse than Place 5/9 unless the house takes vig on the win only." },
      { name: "Lay 5 / 9", pays: "2:3 − 5%", pwin: "60.0%", edge: lE[5], res: "per resolution", grp: "Lay", note: "Wrong-side on 5/9. Edge on amount risked." },
      { name: "Buy 6 / 8", pays: "6:5 − 5%", pwin: "45.5%", edge: bE[6], res: "per resolution", grp: "Buy", note: "Strictly worse than Place 6/8. Never buy the 6 or 8." },
      { name: "Lay 6 / 8", pays: "5:6 − 5%", pwin: "54.5%", edge: lE[6], res: "per resolution", grp: "Lay", note: "Wrong-side on 6/8." },
    ];
  }
  return [
    { name: "Buy 4 / 10", pays: "2 : 1", pwin: "33.3%", edge: bE[4], res: "per resolution", grp: "Buy", note: "Vig-always: 5% of stake charged once at placement. Worse than vig-on-win here — avoid buying 4/10 at a vig-always table." },
    { name: "Lay 4 / 10", pays: "1 : 2", pwin: "66.7%", edge: lE[4], res: "per resolution", grp: "Lay", note: "Vig-always: 5% of the (small) potential win charged once. Cheaper than vig-on-win — the best lay convention." },
    { name: "Buy 5 / 9", pays: "3 : 2", pwin: "40.0%", edge: bE[5], res: "per resolution", grp: "Buy", note: "Vig-always costs more than vig-on-win for every Buy number." },
    { name: "Lay 5 / 9", pays: "2 : 3", pwin: "60.0%", edge: lE[5], res: "per resolution", grp: "Lay", note: "Vig-always is cheaper than vig-on-win for every Lay number." },
    { name: "Buy 6 / 8", pays: "6 : 5", pwin: "45.5%", edge: bE[6], res: "per resolution", grp: "Buy", note: "Still worse than Place 6/8 (1.52%) either way." },
    { name: "Lay 6 / 8", pays: "5 : 6", pwin: "54.5%", edge: lE[6], res: "per resolution", grp: "Lay", note: "Cheapest Lay under vig-always, but Lay 4/10 is cheaper still." },
  ];
}

export function getBetReference(rules) {
  return [...STATIC_BETS, ...fieldBets(rules.fieldTriple), ...buyLayBets(rules.vigAlways)];
}

// Kept for callers that just want the default-rules table (vig-on-win, 3:1 field).
export const BET_REFERENCE = getBetReference({ fieldTriple: true, vigAlways: false });

// Blended edge as odds are added behind a Pass/Don't-Pass line, for every
// table-odds variant the app supports. Pass-side figures are the standard
// published values (Wizard of Odds); Don't-side figures are Monte-Carlo
// simulated here (test/simulate.js "Don't + Nx lay" checks) since they're far
// less commonly tabulated. `id` matches util.js ODDS_MODES so the UI can
// highlight whichever table-odds setting is active.
export const ODDS_LADDER = [
  { id: "flat", label: "Pass, no odds", edge: 1.41 },
  { id: "1x", label: "Pass + 1× odds", edge: 0.85 },
  { id: "2x", label: "Pass + 2× odds", edge: 0.61 },
  { id: "345", label: "Pass + 3-4-5× odds", edge: 0.37 },
  { id: "5x", label: "Pass + 5× odds", edge: 0.33 },
  { id: "10x", label: "Pass + 10× odds", edge: 0.18 },
  { id: "20x", label: "Pass + 20× odds", edge: 0.1 },
  { id: "100x", label: "Pass + 100× odds", edge: 0.02 },
];

export const DONT_LADDER = [
  { id: "flat", label: "Don't Pass, no lay", edge: 1.36 },
  { id: "1x", label: "Don't Pass + 1× lay", edge: 0.68 },
  { id: "2x", label: "Don't Pass + 2× lay", edge: 0.46 },
  { id: "345", label: "Don't Pass + 3-4-5× lay", edge: 0.27 },
  { id: "5x", label: "Don't Pass + 5× lay", edge: 0.23 },
  { id: "10x", label: "Don't Pass + 10× lay", edge: 0.12 },
  { id: "20x", label: "Don't Pass + 20× lay", edge: 0.07 },
  { id: "100x", label: "Don't Pass + 100× lay", edge: 0.01 },
];
